// ignore_for_file: no_leading_underscores_for_local_identifiers

class Item {
  final int itemID;
  final String price;
  final double rating;
  final String category;
  final String itemName;
  final String imageURL;
  bool isFavorated;
  final String decription;
  bool isSelected;

  Item(
      { required this.itemID,
        required this.price,
        required this.category,
        required this.itemName,
        required this.rating,
        required this.imageURL,
        required this.isFavorated,
        required this.decription,
        required this.isSelected});

  static List<Item> itemList = [
    Item(
        itemID: 0,
        price: '25M',
        category: 'Techiques',
        itemName: 'Tractor',
        rating: 3.8,
        imageURL: 'assets/images/tractor.png',
        isFavorated: false,
        decription:'This mid-powered agricultural tractor is a reliable and versatile solution for a variety of farming tasks. Equipped with a powerful diesel engine that delivers high performance in the field.',
        isSelected: false),
    Item(
        itemID: 1,
        price: '80M',
        category: 'Techiques',
        itemName: 'Combine',
        rating: 4.3,
        imageURL: 'assets/images/combine.png',
        isFavorated: false,
        decription:'This combine is perfect for harvesting wheat, barley, corn, rapeseed and other crops, ensuring high productivity and quality of the harvesting process.',
        isSelected: false),  
    Item(
        itemID: 2,
        price: '500K',
        category: 'Techiques',
        itemName: 'Plower',
        rating: 4.0,
        imageURL: 'assets/images/plow.png',
        isFavorated: false,
        decription:'Ploughs are an important tool for preparing the soil for sowing and ensuring optimum conditions for plant development. They are widely used in agriculture and play a key role in the process of cultivating the land before growing crops.',
        isSelected: false),
    Item(
        itemID: 3,
        price: '25M',
        category: 'Techiques',
        itemName: 'Seeder',
        rating: 4.7,
        imageURL: 'assets/images/seeder.png',
        isFavorated: false,
        decription:'A seeder or seeding machine is a specialized piece of equipment designed to accurately and efficiently sow crops in the field. It plays a key role in the planting process.',
        isSelected: false),
    Item(
        itemID: 4,
        price: '5M',
        category: 'Techiques',
        itemName: 'Irrigation',
        rating: 5.0,
        imageURL: 'assets/images/irrigation.png',
        isFavorated: false,
        decription:'Irrigation equipment are systems designed to irrigate agricultural land efficiently and economically. It includes different types of systems such as drip irrigation, sprinkler systems (with sprayers), mobile irrigation trucks and irrigation control systems.',
        isSelected: false),
    Item(
        itemID: 5,
        price: '50M',
        category: 'Techiques',
        itemName: 'Complex',
        rating: 4.1,
        imageURL: 'assets/images/handling.png',
        isFavorated: false,
        decription:'Storage facilities are specialized structures designed to store agricultural crops and other products. They play an important role in agriculture by providing safe and efficient storage of harvested crops until they can be sold or used.',
        isSelected: false),
      Item(
        itemID: 6,
        price: '300K',
        category: 'Techiques',
        itemName: 'Protector',
        rating: 3.8,
        imageURL: 'assets/images/protection.png',
        isFavorated: false,
        decription:'Wheeled sprayers are specialized agricultural equipment designed to effectively apply crop protection products to crops.',
        isSelected: false),
      Item(
        itemID: 7,
        price: '4M',
        category: 'Techiques',
        itemName: 'Drone',
        rating: 4.7,
        imageURL: 'assets/images/precision.png',
        isFavorated: false,
        decription: 'Drones for Precision Farming help growers increase process efficiency, improve land management and minimize the cost of resources such as water, fertilizer and crop protection products.',
        isSelected: false),
      Item(
        itemID: 8,
        price: '1M',
        category: 'Techiques',
        itemName: 'Elevator',
        rating: 3.1,
        imageURL: 'assets/images/elevator.png',
        isFavorated: false,
        decription:'A grain dump elevator, or grain loader, is specialized equipment used on farms and in the agribusiness industry to transfer grain or other agricultural materials from storage or transport vehicles to receiving tanks or processes.',
        isSelected: false),
      Item(
        itemID: 9,
        price: '5M',
        category: 'Techiques',
        itemName: 'Мixer',
        rating: 4.1,
        imageURL: 'assets/images/mixer.png',
        isFavorated: false,
        decription:'It is designed to ensure uniform distribution and mixing of all feed components such as grain, meal, vitamins, minerals, proteins and other additives.',
        isSelected: false),
      Item(
        itemID: 10,
        price: '1.5K',
        category: 'Foods',
        itemName: 'Milk',
        rating: 4.5,
        imageURL: 'assets/images/milk.png',
        isFavorated: false,
        decription:'Milk contains proteins, fats, carbohydrates (mainly lactose), vitamins (A, D, E, K, B group) and minerals (calcium, phosphorus, potassium and others) essential for human health.',
        isSelected: false),
        Item(
        itemID: 11,
        price: '5K',
        category: 'Foods',
        itemName: 'Meat',
        rating: 4.0,
        imageURL: 'assets/images/meat.png',
        isFavorated: false,
        decription:'Meat is a popular and valuable food that is widely used in various cuisines around the world and is part of many balanced diets.',
        isSelected: false),
        Item(
        itemID: 12,
        price: '2K',
        category: 'Foods',
        itemName: 'Mushroom',
        rating: 4.2,
        imageURL: 'assets/images/muchroom.png',
        isFavorated: false,
        decription:'Mushrooms are a natural source of nutrients and give dishes a special flavor and aroma.',
        isSelected: false),
        Item(
        itemID: 13,
        price: '1.6K',
        category: 'Foods',
        itemName: 'Honey',
        rating: 4.4,
        imageURL: 'assets/images/honey.png',
        isFavorated: false,
        decription:'Honey is considered a valuable and useful product, which is widely used in nutrition and used in folk medicine.',
        isSelected: false),
        Item(
        itemID: 14,
        price: '300',
        category: 'Foods',
        itemName: 'Bread',
        rating: 4.8,
        imageURL: 'assets/images/bread2.png',
        isFavorated: false,
        decription:'Bread is a major source of carbohydrates and is a staple food.',
        isSelected: false),
        Item(
        itemID: 15,
        price: '700',
        category: 'Foods',
        itemName: 'Tomato',
        rating: 4.5,
        imageURL: 'assets/images/tomato.png',
        isFavorated: false,
        decription:'Tomatoes are a popular and versatile vegetable that adds vibrant flavor and nutritional benefits to a variety of dishes.',
        isSelected: false),
        Item(
        itemID: 16,
        price: '500',
        category: 'Foods',
        itemName: 'Apple',
        rating: 4.9,
        imageURL: 'assets/images/apple.png',
        isFavorated: false,
        decription:'Apples are widely used in food processing and home cooking due to their versatility, flavor and nutritional properties.',
        isSelected: false),
        Item(
        itemID: 17,
        price: '1.5K',
        category: 'Foods',
        itemName: 'Cherry',
        rating: 4.0,
        imageURL: 'assets/images/cherry.png',
        isFavorated: false,
        decription:'Order fresh cherries now to enjoy summer flavors and add brightness to your table.',
        isSelected: false),
        Item(
        itemID: 18,
        price: '1.8K',
        category: 'Foods',
        itemName: 'Grapes',
        rating: 3.4,
        imageURL: 'assets/images/grapes.png',
        isFavorated: false,
        decription:'We offer you to enjoy fresh and juicy grapes of high quality! Our grapes are perfect for eating fresh, creating fruit salads, making appetizers and desserts, or for making homemade wines and jams.',
        isSelected: false),
        Item(
        itemID: 19,
        price: '100',
        category: 'Foods',
        itemName: 'Corn',
        rating: 4.1,
        imageURL: 'assets/images/corn1.png',
        isFavorated: false,
        decription:'Corn is an excellent source of dietary fiber, vitamins (especially vitamin C and vitamin B), minerals (such as potassium), and antioxidants to support a healthy lifestyle.',
        isSelected: false),
        Item(
        itemID: 20,
        price: '30K',
        category: 'Tools',
        itemName: 'Set',
        rating: 4.2,
        imageURL: 'assets/images/set.png',
        isFavorated: false,
        decription:'This tool set is specially designed for use in agriculture, vegetable gardens and orchards, providing effective support for tillage, plant care and a variety of agronomic tasks.',
        isSelected: false),
        Item(
        itemID: 21,
        price: '100K',
        category: 'Tools',
        itemName: 'Spray',
        rating: 4.6,
        imageURL: 'assets/images/spray.png',
        isFavorated: false,
        decription:'Crop protection spray is an effective means of controlling pests, diseases and weeds in agriculture. It provides reliable protection and helps to maintain plant health and growth.',
        isSelected: false),
        Item(
        itemID: 22,
        price: '400K',
        category: 'Tools',
        itemName: 'Cart',
        rating: 4.3,
        imageURL: 'assets/images/agro_cart.png',
        isFavorated: false,
        decription:'The electric cart is a versatile solution for transporting goods and facilitating heavy work on the farm or in agriculture. It is equipped with an electric motor, making it efficient and economical for use in various agricultural operations.',
        isSelected: false),
        Item(
        itemID: 23,
        price: '30K',
        category: 'Tools',
        itemName: 'Soil Meter',
        rating: 4.1,
        imageURL: 'assets/images/soil_meter.png',
        isFavorated: false,
        decription:'The Soil Meter is an innovative device designed to accurately analyze and monitor soil parameters on your agricultural plot. It is an indispensable tool for optimizing crop yields and ensuring healthy plant growth.',
        isSelected: false),
        Item(
        itemID: 24,
        price: '185K',
        category: 'Tools',
        itemName: 'Mower',
        rating: 4.1,
        imageURL: 'assets/images/gazon.png',
        isFavorated: false,
        decription:'Ensure quality lawn care with our lawn mower, which will provide an efficient and professional treatment of the green cover on your property.',
        isSelected: false),
        Item(
        itemID: 25,
        price: '5K',
        category: 'Tools',
        itemName: 'Shovel',
        rating: 2.3,
        imageURL: 'assets/images/shovel.png',
        isFavorated: false,
        decription:' The shovel is a reliable and efficient tool for various agricultural tasks such as digging, planting, harvesting and other work on the farm or vegetable garden. It provides convenience, durability and high productivity when working the soil.',
        isSelected: false),
        Item(
        itemID: 26,
        price: '25K',
        category: 'Tools',
        itemName: 'Scissors',
        rating: 3.9,
        imageURL: 'assets/images/scissors.png',
        isFavorated: false,
        decription:' Improve your garden maintenance with electric shears that make pruning and plant care quick, easy and efficient.',
        isSelected: false),
        Item(
        itemID: 27,
        price: '100K',
        category: 'Tools',
        itemName: 'Greenhouse',
        rating: 4.0,
        imageURL: 'assets/images/green_house.png',
        isFavorated: false,
        decription:'The greenhouse is the ideal solution for growing plants in a controlled environment, providing optimal conditions for development and protection from unfavorable weather conditions. It is an indispensable tool for increasing yields and extending the growing season.',
        isSelected: false),
        Item(
        itemID: 28,
        price: '25K',
        category: 'Tools',
        itemName: 'Respirator',
        rating: 3.5,
        imageURL: 'assets/images/respirator.png',
        isFavorated: false,
        decription:'The respirator is a reliable and effective means of respiratory protection for agricultural work. It keeps the operator safe from harmful particles, dust, allergens and chemicals that may be present in the air on farms and in rural areas.',
        isSelected: false),
        Item(
        itemID: 29,
        price: '4K',
        category: 'Tools',
        itemName: 'Gloves',
        rating: 5.0,
        imageURL: 'assets/images/gloves.png',
        isFavorated: false,
        decription:'Gloves are designed to provide protection and comfort during agricultural work. They are ideal for tilling the soil, tending plants, harvesting and other tasks on the farm or vegetable garden. Our gloves provide reliable hand protection and allow you to perform a variety of agricultural operations efficiently.',
        isSelected: false),
        Item(
        itemID: 30,
        price: '90',
        category: 'Seeds',
        itemName: 'Wheat',
        rating: 3.3,
        imageURL: 'assets/images/wheat.png',
        isFavorated: false,
        decription:'Wheat seeds, which are the ideal choice for agricultural crops. These seeds provide high yields, excellent grain quality and resistance to unfavorable weather conditions.',
        isSelected: false),
        Item(
        itemID: 31,
        price: '70',
        category: 'Seeds',
        itemName: 'Corn',
        rating: 3.9,
        imageURL: 'assets/images/corn.png',
        isFavorated: false,
        decription:'A corn grain that is excellent for sowing on agricultural plots. This versatile grain is used to grow corn for grain, livestock feed, and other products such as corn syrup and starch.',
        isSelected: false),
        Item(
        itemID: 32,
        price: '250',
        category: 'Seeds',
        itemName: 'Herb',
        rating: 4.2,
        imageURL: 'assets/images/herb.png',
        isFavorated: false,
        decription:'These seeds provide a rich and varied food for horses, ensuring optimal conditions for their health, nutrition and activity.',
        isSelected: false),
        Item(
        itemID: 33,
        price: '1250',
        category: 'Seeds',
        itemName: 'Strawberry',
        rating: 3.4,
        imageURL: 'assets/images/strawberry.png',
        isFavorated: false,
        decription:'Strawberry seeds are an excellent choice for growing delicious and juicy berries right on your plot. These seeds provide the opportunity to grow strawberries with great flavor and aroma, suitable for both home and commercial growing.',
        isSelected: false),
        Item(
        itemID: 34,
        price: '780',
        category: 'Seeds',
        itemName: 'BB',
        rating: 4.4,
        imageURL: 'assets/images/cyan.png',
        isFavorated: false,
        decription:'The Bachelor Button flower, also known as carnation or cornflower, is an attractive and easily recognizable plant with bright blue flowers. This flower is a popular choice for landscaping gardens, flower beds and lawns due to its beauty and unpretentiousness.',
        isSelected: false),
        Item(
        itemID: 35,
        price: '600',
        category: 'Seeds',
        itemName: 'Sunflower',
        rating: 4.9,
        imageURL: 'assets/images/sunflower.png',
        isFavorated: false,
        decription:'Sunflower seeds are an excellent choice for growing this popular crop. Sunflowers are known for their bright and large flowers and are also in demand as a source of food, oil and animal feed.',
        isSelected: false),
        Item(
        itemID: 36,
        price: '5k',
        category: 'Fertilizers',
        itemName: 'Marphyl',
        rating: 4.2,
        imageURL: 'assets/images/marphyl.png',
        isFavorated: false,
        decription:'Marphyl Liquid Fertilizer is an innovative and effective fertilizer made from seaweed and enriched with micronutrients. This unique fertilizer offers plants a full range of nutrients necessary for healthy growth, disease resistance and high yields.',
        isSelected: false),
        Item(
        itemID: 37,
        price: '8k',
        category: 'Fertilizers',
        itemName: 'Organic',
        rating: 4.3,
        imageURL: 'assets/images/organic.png',
        isFavorated: false,
        decription:'Compost is a high quality organic fertilizer derived from recycled organic materials such as food scraps, vegetable waste, leaves and other biodegradable materials. This fertilizer is an effective way to improve soil fertility, enrich the soil with nutrients and support healthy plant growth.',
        isSelected: false),
        Item(
        itemID: 38,
        price: '31k',
        category: 'Fertilizers',
        itemName: 'Booster',
        rating: 4.9,
        imageURL: 'assets/images/booster.png',
        isFavorated: false,
        decription:'"Booster Plant" is a highly effective organic fertilizer specially formulated to stimulate plant growth and development. It contains a unique combination of natural ingredients that nourish roots, promote fruit formation and improve plant resistance to stressful conditions.',
        isSelected: false),
        Item(
        itemID: 39,
        price: '10k',
        category: 'Fertilizers',
        itemName: 'Amino ',
        rating: 1.9,
        imageURL: 'assets/images/amino.png',
        isFavorated: false,
        decription:'Amino acid fertilizers are an innovative way to provide plants with all the nutrients they need for healthy growth, development and yield. These fertilizers contain a complex of amino acids, which are the basic building blocks of protein molecules and play a key role in plant biochemical processes.',
        isSelected: false),
        Item(
        itemID: 40,
        price: '20k',
        category: 'Fertilizers',
        itemName: 'Fiddle',
        rating: 3.4,
        imageURL: 'assets/images/fiddle.png',
        isFavorated: false,
        decription:'Fertilizers with long-lasting effect are designed to provide continuous nourishment and support for plants over an extended period, ensuring their healthy growth and development. These fertilizers release nutrients gradually, sustaining plants with essential elements they need for robust growth and improved resilience.',
        isSelected: false),
  ];

  static List<Item> getFavoritedItems(){
    List<Item> _favList = Item.itemList;
    return _favList.where((element) => element.isFavorated == true).toList();
  }

  static List<Item> addedToCartItems(){
    List<Item> _selectedItems = Item.itemList;
    return _selectedItems.where((element) => element.isSelected == true).toList();
  }
} 