// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5nijPv_gfOiq6lZ-qhCzm9jlDaNjBfok',
    appId: '1:98396493170:web:9539ab3e62520dc3d2b9eb',
    messagingSenderId: '98396493170',
    projectId: 'agro-shop-657b5',
    authDomain: 'agro-shop-657b5.firebaseapp.com',
    storageBucket: 'agro-shop-657b5.appspot.com',
    measurementId: 'G-KJX0XRNFX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGajysYTnmVI-DWV15Xu-AENCiE2djpc4',
    appId: '1:98396493170:android:54b13389bfed423ed2b9eb',
    messagingSenderId: '98396493170',
    projectId: 'agro-shop-657b5',
    storageBucket: 'agro-shop-657b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_HvBncl6q8vqu8TFt1kqj1iYUJhH_XUY',
    appId: '1:98396493170:ios:cafa75ad7d4dde86d2b9eb',
    messagingSenderId: '98396493170',
    projectId: 'agro-shop-657b5',
    storageBucket: 'agro-shop-657b5.appspot.com',
    iosBundleId: 'com.example.agroShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_HvBncl6q8vqu8TFt1kqj1iYUJhH_XUY',
    appId: '1:98396493170:ios:cafa75ad7d4dde86d2b9eb',
    messagingSenderId: '98396493170',
    projectId: 'agro-shop-657b5',
    storageBucket: 'agro-shop-657b5.appspot.com',
    iosBundleId: 'com.example.agroShop',
  );
}
